sudo: required
language: elixir
elixir:
  - 1.7.3
otp_release:
  - '20.3'
script:
  - mix test
  - mix credo
  - "travis_wait 30 mix dialyzer --plt"
  - mix dialyzer --halt-exit-status
cache:
  - directories:
      - .dialyzer
